Repository kubernetes/k8s.io, pull requests merged in 2019-11, with the labels that each got.

#443 add project to test GCR auditing mechanism
  infra/gcp/ensure-prod-storage.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, wg/k8s-infra

#377 add scripts for backups
  infra/gcp/backup_tools/README.md
  infra/gcp/backup_tools/backup.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, wg/k8s-infra

#452 Update Release Manager groups membership
  groups/groups.yaml
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/release, size/M, wg/k8s-infra

#454 releng: Revoke Sascha's temporary access to GCP
  groups/groups.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, wg/k8s-infra

#453 Enable clusterViewer for k8s users
  infra/gcp/ensure-main-project.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, wg/k8s-infra

#457 Update Bob Killen's email addresses.
  groups/groups.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, wg/k8s-infra

#458 Update Stephen Augustus' email address
  groups/groups.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, wg/k8s-infra

#462 Fix groups settings for steering list
  groups/groups.yaml
  groups/reconcile.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, wg/k8s-infra

#467 Add members to multitenancy working group
  groups/groups.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, wg/k8s-infra

#471 Add Loodse to distributors-announce
  groups/groups.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, wg/k8s-infra

#472 Fix rjbez17 e-mail address
  groups/groups.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, wg/k8s-infra

#473 Promote CAPA v0.4.5
  k8s.gcr.io/images/k8s-staging-cluster-api-aws/images.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, wg/k8s-infra

#470 backup.sh: do not depend on docker
  infra/gcp/backup_tools/backup.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, wg/k8s-infra

#474 add linusa (listx@ on GitHub) to k8s-infra-alerts@kubernetes.io
  groups/groups.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, wg/k8s-infra

#475 backup.sh: add tracing for more verbosity
  infra/gcp/backup_tools/backup.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, wg/k8s-infra

#477 add backup test
  infra/gcp/backup_tools/README.md
  infra/gcp/backup_tools/backup.sh
  infra/gcp/backup_tools/backup_images_expected.yaml
  infra/gcp/backup_tools/backup_lib.sh
  infra/gcp/backup_tools/backup_prod.sh
  infra/gcp/backup_tools/backup_test.sh
Labels: approved, cncf-cla: yes, lgtm, size/L, wg/k8s-infra

#478 Add image for CAPA v0.4.6
  k8s.gcr.io/images/k8s-staging-cluster-api-aws/images.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, wg/k8s-infra
